- pip:
    - aiohttp==3.6.2
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - async-timeout==3.0.1
    - beautifulsoup4==4.9.1
    - blessings==1.7
    - cachetools==4.1.1
    - chardet==3.0.4
    - cirpy==1.0.2
    - click==7.0
    - colorama==0.4.1
    - colorful==0.5.4
    - configparser==5.0.0
    - docker-pycreds==0.4.0
    - drive-cli==2.1.0
    - filelock==3.0.12
    - gdown==3.12.2
    - gensim==3.8.2
    - gitdb==4.0.5
    - gitpython==3.1.7
    - google==3.0.0
    - google-api-core==1.22.1
    - google-api-python-client==1.7.8
    - google-auth==1.20.1
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.31.0
    - hiredis==1.1.0
    - httplib2==0.12.1
    - idna==2.8
    - ipdb==0.13.3
    - ipywidgets==7.6.3
    - jupyterlab-widgets==1.0.0
    - molvs==0.1.1
    - msgpack==1.0.0
    - multidict==4.7.6
    - nvidia-ml-py3==7.352.0
    - oauth2client==4.1.3
    - opencensus==0.7.10
    - opencensus-context==0.1.1
    - pathtools==0.1.2
    - pick==0.6.4
    - prettytable==0.7.2
    - promise==2.3
    - psutil==5.7.2
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfiglet==0.8.post1
    - pyyaml==5.3.1
    - ray==1.0.1.post1
    - redis==3.4.1
    - requests==2.21.0
    - rsa==4.6
    - ruffus==2.8.4
    - seaborn==0.11.1
    - sentry-sdk==0.16.2
    - shortuuid==1.0.1
    - smart-open==5.1.0
    - smmap==3.0.4
    - soupsieve==2.0.1
    - subprocess32==3.5.4
    - tabulate==0.8.7
    - uritemplate==3.0.1
    - urllib3==1.25.10
    - wandb==0.10.22
    - watchdog==0.10.3
    - widgetsnbextension==3.5.1
    - yarl==1.5.1
